
trigger:
- master

variables:
  system.debug: true

jobs:
- job: ubuntu_web_assembly_hosted
  pool:
    name: Hosted Ubuntu 1604
  container: 
    image: trzeci/emscripten:latest
  steps:
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: Use CMakeSettings.json
      inputs:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        configurationRegexFilter: 'Emscripten Linux Release'
        cmakeWrapperCommand: emcmake

- job: ubuntu_native_release_x64_hosted
  pool:
    vmImage: ubuntu-latest
  steps:
    - script: |
        sudo apt-get update && sudo apt-get install xorg-dev libglu1-mesa-dev libalut-dev |
        echo "##vso[task.setvariable variable=CC]`which gcc-7`" |
        echo "##vso[task.setvariable variable=CXX]`which g++-7`"
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        configurationRegexFilter: 'Linux-Release'

- job: macos_native_release_x64_hosted
  pool:
    name:  Hosted macOS
  steps:
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'CMakeSettings.json'
      inputs:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        configurationRegexFilter: 'Linux-Release'
